on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup requirements
        run: |
          sudo apt-get update
          sudo apt-get install gcc libgtk-3-dev libayatana-appindicator3-dev libx11-dev xorg-dev
      - name: Download rules
        run: curl https://raw.githubusercontent.com/ClearURLs/Rules/master/data.min.json -o rules.json
      - uses: actions/setup-go@v3
        with:
          go-version: 'stable'
      - run: go build
