on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm64]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: arm64
            goos: windows
          - goarch: arm64 # the systray library currently doesn't support Apple Silicon
            goos: darwin
    steps:
      - uses: actions/checkout@v3
      - name: Download rules
        run: curl https://raw.githubusercontent.com/ClearURLs/Rules/master/data.min.json -o rules.json
      - uses: wangyoucao577/go-release-action@v1.34
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          ldflags: "-s -w ${{ matrix.goos == 'windows' && '-H=windowsgui' || '' }}"
          pre_command: echo "deb http://deb.debian.org/debian stretch-backports main" >> /etc/apt/sources.list && apt-get update && apt-get install -y pkg-config gcc libgtk-3-dev libayatana-appindicator3-dev libx11-dev xorg-dev
          md5sum: false
          sha256sum: true
